var quiz = [
    {q: 'Quando foi lançado a versão 1.6 de Counter Strike:', opcao: ['1999', '2000', '2003'], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
    {q: '', opcao: [], resposta: []},
]